# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install
            pip install pillow
            pip install -U pytest
      
      - run:
          name: Make Logs Directory
          command: |
            mkdir ~/logs

      # look for TODOs
      - run:
          name: Find TODOs
          command: |
            . venv/bin/activate
            python .circleci/todo.py
      
      - store_artifacts:
          path: todo.txt
          destination: todo.txt

      # run tests!
      - run:
          name: Run Tests and Save Results
          command: |
            . venv/bin/activate
            python -m pytest vacuumworld/test
      